version: '3.7'

services: 

    jenkins-docker:

        image: 'docker:dind'

        privileged: true

        networks:
            jenkins:
                aliases: 
                    - docker

        environment:
            - 'DOCKER_TLS_CERTDIR=/certs'

        volumes:
            - ./home_folder:/home
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home

        container_name: jenkins-docker

    jenkins-tutorial:

        image: 'jenkinsci/blueocean:latest'

        privileged: true

        networks:
            - jenkins

        environment:
            - 'DOCKER_HOST=tcp://docker:2376'
            - 'DOCKER_CERT_PATH=/certs/client'
            - 'DOCKER_TLS_VERIFY=1'

        volumes:
            - ./home_folder:/home
            - jenkins-docker-certs:/certs/client:ro
            - jenkins-data:/var/jenkins_home

        ports:
            - 8080:8080

        container_name: jenkins-tutorial


networks:
    jenkins:

volumes:
    jenkins-data:
    jenkins-docker-certs:    